
# it is very imporant to specify a large enough tmp file in the abra2 options below.
# Note that on many servers the user's home directory is too small to be suitable for the tmp file.
# Note also that it is used by other rules as well, not only abra2

#this CSV file specifies run+library to fastq file relation and other metadata
samples: "metadata/sample2runlib.csv"
sample_sets: []

# the mode feature is not yet implemented
# mode: s or c
#   s = samples
#   c = cohort
mode: s

# specify the path(s) to your reference genome(s) and give them each a name
refs:
  GCF_004118075.1_ASM411807v1: genomes_and_annotations/GCF_004118075.1_ASM411807v1/GCF_004118075.1_ASM411807v1_genomic.fna
#  my_reference_genome_2:

# configuration options for the QC rules:
# Adapter "_DEFAULT_" will be used. Replace with your respective adapter sequences, don't remove output related options from "extra"!
qc:
  _DEFAULT_:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  Truseq:
    adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  Nextera:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25

  extra: "--combined-output --interleaved --interleaved-output --trimns --trimqualities --trimwindows 10"

# configuration options for the indel realigner abra2. this is also the place to specify the location of the tmp file.
abra2:
  memory:
    - Xmx24g
  release:
    - envs/abra2.jar
  temp:
    - /data/norman/tmp/
  threads:
    - 10
  regions:
    - metadata/contigs_of_interest.bed

#TODO move temp variable because other tools are using it as well!

# configure options for the varcall rules: which aligners and callers to use as well as their parameters
# this is also the place to configure the filters to run on the vcf file to produce filtered vcf file(s).
varcall:
  aligners:
    - bwa
#    - ngm
  callers:
    #- mpileup
    - freebayes
  refs:
    - GCF_004118075.1_ASM411807v1
#    - my_reference_genome_2
  samplesets:
    - all_samples
# Paramters
  minmapq:
    bwa: 30
    ngm: 10
  minbq: 15
  theta_prior: 0.001 # default for freebayes is 0.001, make sure you read the respective manuals
  chunksize: 10000000 # it is in these-sized-chunks that freebayes runs. This is implemented for better parallelisation
# Variant Filters
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 20 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.20 &&
          MAF >= 0.01'
    # Above strict requires a presence rate of >20%, which isn't ideal when running on more than 1 mutant. Read the respective manual (bcftools view)

# configuration options for the snpEff rule:
# specify the name of your snpeff directory. it is expeted to reside as snpeffdata in genomes_and_annotations. (see genomes_and_annotations/readme), currently only one reference genome can be used. 'filter' refers to the input vcf file and hence defines the desired variant filter to use upstream of snpeff.
snpeff:
  name: GCF_004118075.1_ASM411807v1_snpeff
  filter: strict

  #TODO: change so that more than one reference genome can be used
  #TODO: add a rule that prepares the reference genome and annotation for SNPEFF
  #  my_reference_genome_1: genomes_and_annotations/my_reference_genome_1/genome_1.gff_or_gtf

# configure options when runnign the de-novo rule. This is unrelated to any mapping or varcalling. For normal application, leave as is.
denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  sourmash_sketchsize: 100000
  ksize: 21
  kwip_sets:
    - all_samples
  mash_sets: # we can subset from everything for (sour)mash
    - all_samples
  sourmash_sets: []

##############################################################################

# configuration options for hte mapping rule. using those will only have an effect when runnign the mapping rule separately, which is not a recommended use case.
#When invoking the mapping rules through the varcall rule, the parameter specified in the varcall rule above take precedence.
mapping:
  aligners:
    - bwa
#    - ngm
  refs:
    - my_reference_genome_1
#    - my_reference_genome_2
  samplesets:
    - all_samples
  ngm:
    sensitivity: 0.5

################################################################################
#below is not implemented yet
known_variants:
  # Optional: Path to a VCF file of known variants. Variant IDs from this file will be transferred to the new VCF file
  # known-variants: genomes_and_annotations/my_reference_genome_1/known_variants.vcf.gz
  #this feature is currently not yet implemented
  # TODO implement "vcf annotate rule", ideally for more than one reference genome

LB-impute:
  mem: Xmx3g
  release: envs/LB-Impute.jar
  method: impute
  extra: "-readerr  0.05 -genotypeerr 0.05 -recombdist 1000000 -window 5 -offspringimpute "
  parents: "D2,con"
