
samples: "metadata/sample2runlib.csv"

sample_sets: []

# mode: s or c
#   s = samples
#   c = cohort
mode: s


refs:
  GCF_004118075.1_ASM411807v1: genomes_and_annotations/GCF_004118075.1_ASM411807v1/GCF_004118075.1_ASM411807v1_genomic.fna
#  my_reference_genome_2:

  
snpeff:
  name: GCF_004118075.1_ASM411807v1_snpeff
  filter: strict

  #TODO: change so that more than one reference genome can be used
  #TODO: add a rule that prepares the reference genome and annotation for SNPEFF
  #  my_reference_genome_1: genomes_and_annotations/my_reference_genome_1/genome_1.gff_or_gtf


known_variants: 
  # Optional: Path to a VCF file of known variants. Variant IDs from this file will be transferred to the new VCF file
  # known-variants: genomes_and_annotations/my_reference_genome_1/known_variants.vcf.gz

  # TODO implement "vcf annotate rule", ideally for more than one reference genome


qc:
  _DEFAULT_:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  Truseq:
    adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  LBEmel:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25


  extra: "--combined-output --interleaved --interleaved-output --trimns --trimqualities --trimwindows 10"


mapping:
  aligners:
    - bwa
#    - ngm
  refs:
    - my_reference_genome_1
#    - my_reference_genome_2
  samplesets:
    - all_samples
  ngm:
    sensitivity: 0.5

abra2:
  memory:
    - Xmx24g
  release:
    - envs/abra2.jar
  temp:
    - /data/norman/tmp/
  #TODO move temp variable because other tools are using it as well!

  threads:
    - 10
  regions:
    - metadata/contigs_of_interest.bed


LB-impute:
  mem: Xmx3g
  release: envs/LB-Impute.jar
  method: impute
  extra: "-readerr  0.05 -genotypeerr 0.05 -recombdist 1000000 -window 5 -offspringimpute "
  parents: "D2,con"


denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  sourmash_sketchsize: 100000
  ksize: 21
  kwip_sets:
    - all_samples
  mash_sets: # we can subset from everything for (sour)mash
    - all_samples
  sourmash_sets: []


varcall:
  minmapq:
    bwa: 30
    ngm: 10
  minbq: 15
  theta_prior: 0.001 # default for freebayes is 0.001, make sure you read the respective manuals
  chunksize: 10000000 # it is in these-sized-chunks that freebayes runs. This is implemented for better parallelisation
  aligners:
    - bwa
#    - ngm
  callers:
    #- mpileup
    - freebayes
  refs:
    - GCF_004118075.1_ASM411807v1
#    - my_reference_genome_2
  samplesets:
    - all_samples
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 20 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.20 &&
          MAF >= 0.01'
    # Above is presence rate, >20%
